model_type: att_unet        # "unet", "unetpp", or "att_unet"
data_dir: data
batch_size: 8
max_epochs: 20
encoder_name: resnet34      # ignored for att_unet
lr: 0.001
pretrained: true
experiment_name: attunet_exp
precision: 32-true
freeze_encoder: true
use_focal_loss: true
class_weights: null     