data_dir: data
batch_size: 8
max_epochs: 32
encoder_name: resnet34
lr: 0.001
pretrained: true
use_unetplusplus: false
experiment_name: unet
precision: 32-true
freeze_encoder: true
use_focal_loss: true
class_weights: null     
model_type: unet